// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDz17fvfxTXlpue7GYZzLgid1L5OqkGUU',
    appId: '1:288067271642:web:67ed9aaeb96f94bd815ee3',
    messagingSenderId: '288067271642',
    projectId: 'yama-42470',
    authDomain: 'yama-42470.firebaseapp.com',
    storageBucket: 'yama-42470.appspot.com',
    measurementId: 'G-XG3B6P1S3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB46aCF9Lo03sUb7elKGVeGM1rSyshu3s',
    appId: '1:288067271642:android:ae5f441f0cde78bf815ee3',
    messagingSenderId: '288067271642',
    projectId: 'yama-42470',
    storageBucket: 'yama-42470.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE0Aqi6NHKpfuNsZWDU3YLThpOMoOh81E',
    appId: '1:288067271642:ios:b1761b64b122d3a3815ee3',
    messagingSenderId: '288067271642',
    projectId: 'yama-42470',
    storageBucket: 'yama-42470.appspot.com',
    iosClientId: '288067271642-ukc0bgvpvjl6gh74ngbcke8a4kp8kkbo.apps.googleusercontent.com',
    iosBundleId: 'com.example.yama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE0Aqi6NHKpfuNsZWDU3YLThpOMoOh81E',
    appId: '1:288067271642:ios:e4f281c0ee52d63b815ee3',
    messagingSenderId: '288067271642',
    projectId: 'yama-42470',
    storageBucket: 'yama-42470.appspot.com',
    iosClientId: '288067271642-5fphm34h4o5gtadjm36kqlsnkthiv07c.apps.googleusercontent.com',
    iosBundleId: 'com.example.yama.RunnerTests',
  );
}
